export const enum RuleOperator {
  EQUALS = 'EQUALS',

  CONTAINS = 'CONTAINS',

  NOTCONTAINS = 'NOTCONTAINS',

  GREATEROREQUALTHAN = 'GREATEROREQUALTHAN',

  LESSOREQUALTHAN = 'LESSOREQUALTHAN',
}
